### ISSUE TITLE
PM 4.0

### ISSUE THREAD

**Issue by tunikakeks** [Cosmoverse/mcMMO#4]
How to get PocketMine API 4.0?

**Comment by IceCruelStuff** [comment]
Use the PocketMine master branch
https://github.com/pmmp/PocketMine-MP/tree/master

**Comment by tunikakeks** [comment]
And how to get the new Vendor folder?

**Comment by IceCruelStuff** [comment]
Just follow the instructions in [BUILDING.md]https://github.com/pmmp/PocketMine-MP/blob/master/BUILDING.md()
