### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Grytic** [Cosmoverse/mcMMO#5]
1. Error: "Call to a member function close() on null" (EXCEPTION) in "plugins/mcMMO_dev20.phar/src/cosmicpe/mcmmo/McMMO" at line 58
2. Error: "Class 'BlockHorizons\Fireworks\item\Fireworks' not found" (EXCEPTION) in "plugins/mcMMO_dev-20.phar/src/cosmicpe/mcmmo/integration/IntegrationManager" at line 23

**Comment by Muqsit** [comment]
Too vague, send backtrace please.
